server:
  port: 8080

crawler:
  maxDepth: 10
  threadCount: 4
  crawlDelayMillis: 1000
  maxPagesPerDomain: 5000
  userAgent: "Mozilla/5.0 (compatible; NitionBot/1.0; +http://localhost)"
  connectionTimeout: 10000
  maxRetries: 3

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect